name: Build and Test ROS 2 Rust Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distro: [foxy, humble]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup ROS Environment
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: "" # Optional: Add if you have a .repos file for additional dependencies
          workspace-subdirectory: ""

      - name: Install ROS Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y python3-rosdep python3-vcstool
          sudo rosdep init
          rosdep update

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install ROS 2 Rust Dependencies
        run: |
          rustup component add rustfmt
          rustup target add aarch64-unknown-linux-gnu  # Modify if your target differs
          cargo install --git https://github.com/ros2-rust/ros2_rust.git

      - name: Build Project
        run: cargo build --release

      - name: Run Tests
        run: cargo test
