name: Build ROS2 Rust Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ros_distro: ["foxy", "humble"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y curl gnupg lsb-release

          # Add ROS 2 apt repository
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
          sudo apt update

          # Install ROS 2 and dependencies
          sudo apt install -y ros-${{ matrix.ros_distro }}-desktop python3-colcon-common-extensions

      - name: Set up ROS environment
        run: echo "source /opt/ros/${{ matrix.ros_distro }}/setup.bash" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install ros2_rust dependencies
        run: |
          sudo apt install -y ros-${{ matrix.ros_distro }}-std-msgs

      - name: Build Rust project
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          export RUSTFLAGS="--cfg=rclrs"
          cargo build --verbose

      - name: Test ROS 2 Node
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          cargo test

